committing live npm files to Live branch

diff --git a/npm/Makefile b/npm/Makefile
--- a/npm/Makefile
+++ b/npm/Makefile
@@ -1,9 +1,6 @@
 # vim: set softtabstop=2 shiftwidth=2:
 SHELL = bash
 
-PUBLISHTAG = $(shell node scripts/publish-tag.js)
-BRANCH = $(shell git rev-parse --abbrev-ref HEAD)
-
 markdowns = $(shell find doc -name '*.md' | grep -v 'index') README.md
 
 html_docdeps = html/dochead.html \
@@ -15,6 +12,10 @@ cli_mandocs = $(shell find doc/cli -name '*.md' \
                |sed 's|.md|.1|g' \
                |sed 's|doc/cli/|man/man1/|g' ) \
                man/man1/npm-README.1
+
+api_mandocs = $(shell find doc/api -name '*.md' \
+               |sed 's|.md|.3|g' \
+               |sed 's|doc/api/|man/man3/|g' )
 
 files_mandocs = $(shell find doc/files -name '*.md' \
                |sed 's|.md|.5|g' \
@@ -32,6 +33,10 @@ cli_htmldocs = $(shell find doc/cli -name '*.md' \
                 |sed 's|doc/cli/|html/doc/cli/|g' ) \
                 html/doc/README.html
 
+api_htmldocs = $(shell find doc/api -name '*.md' \
+                |sed 's|.md|.html|g' \
+                |sed 's|doc/api/|html/doc/api/|g' )
+
 files_htmldocs = $(shell find doc/files -name '*.md' \
                   |sed 's|.md|.html|g' \
                   |sed 's|doc/files/|html/doc/files/|g' ) \
@@ -43,9 +48,9 @@ misc_htmldocs = $(shell find doc/misc -name '*.md' \
                  |sed 's|doc/misc/|html/doc/misc/|g' ) \
                  html/doc/index.html
 
-mandocs = $(cli_mandocs) $(files_mandocs) $(misc_mandocs)
+mandocs = $(api_mandocs) $(cli_mandocs) $(files_mandocs) $(misc_mandocs)
 
-htmldocs = $(cli_htmldocs) $(files_htmldocs) $(misc_htmldocs)
+htmldocs = $(api_htmldocs) $(cli_htmldocs) $(files_htmldocs) $(misc_htmldocs)
 
 all: doc
 
@@ -53,10 +58,10 @@ latest:
 	@echo "Installing latest published npm"
 	@echo "Use 'make install' or 'make link' to install the code"
 	@echo "in this folder that you're looking at right now."
-	node cli.js install -g -f npm ${NPMOPTS}
+	node cli.js install -g -f npm
 
-install: all
-	node cli.js install -g -f ${NPMOPTS}
+install: docclean all
+	node cli.js install -g -f
 
 # backwards compat
 dev: install
@@ -64,7 +69,7 @@ dev: install
 link: uninstall
 	node cli.js link -f
 
-clean: markedclean marked-manclean doc-clean uninstall
+clean: ronnclean doc-clean uninstall
 	rm -rf npmrc
 	node cli.js cache clean
 
@@ -73,27 +78,28 @@ uninstall:
 
 doc: $(mandocs) $(htmldocs)
 
-markedclean:
-	rm -rf node_modules/marked node_modules/.bin/marked .building_marked
-
-marked-manclean:
-	rm -rf node_modules/marked-man node_modules/.bin/marked-man .building_marked-man
+ronnclean:
+	rm -rf node_modules/ronn node_modules/.bin/ronn .building_ronn
 
 docclean: doc-clean
 doc-clean:
 	rm -rf \
-    .building_marked \
-    .building_marked-man \
+    .building_ronn \
     html/doc \
+    html/api \
     man
 
-# use `npm install marked-man` for this to work.
+# use `npm install ronn` for this to work.
 man/man1/npm-README.1: README.md scripts/doc-build.sh package.json
 	@[ -d man/man1 ] || mkdir -p man/man1
 	scripts/doc-build.sh $< $@
 
 man/man1/%.1: doc/cli/%.md scripts/doc-build.sh package.json
 	@[ -d man/man1 ] || mkdir -p man/man1
+	scripts/doc-build.sh $< $@
+
+man/man3/%.3: doc/api/%.md scripts/doc-build.sh package.json
+	@[ -d man/man3 ] || mkdir -p man/man3
 	scripts/doc-build.sh $< $@
 
 man/man5/npm-json.5: man/man5/package.json.5
@@ -125,9 +131,12 @@ html/doc/cli/%.html: doc/cli/%.md $(html_docdeps)
 	@[ -d html/doc/cli ] || mkdir -p html/doc/cli
 	scripts/doc-build.sh $< $@
 
+html/doc/api/%.html: doc/api/%.md $(html_docdeps)
+	@[ -d html/doc/api ] || mkdir -p html/doc/api
+	scripts/doc-build.sh $< $@
+
 html/doc/files/npm-json.html: html/doc/files/package.json.html
 	cp $< $@
-
 html/doc/files/npm-global.html: html/doc/files/npm-folders.html
 	cp $< $@
 
@@ -140,43 +149,66 @@ html/doc/misc/%.html: doc/misc/%.md $(html_docdeps)
 	scripts/doc-build.sh $< $@
 
 
-marked: node_modules/.bin/marked
 
-node_modules/.bin/marked:
-	node cli.js install marked --no-global
+ronn: node_modules/.bin/ronn
 
-marked-man: node_modules/.bin/marked-man
-
-node_modules/.bin/marked-man:
-	node cli.js install marked-man --no-global
+node_modules/.bin/ronn:
+	node cli.js install ronn --no-global
 
 doc: man
 
-man: $(cli_docs)
+man: $(cli_docs) $(api_docs)
 
 test: doc
 	node cli.js test
 
-tag:
-	npm tag npm@$(PUBLISHTAG) latest
-
-ls-ok:
-	node . ls >/dev/null
-
-gitclean:
-	git clean -fd
-
-publish: gitclean ls-ok link doc-clean doc
+publish: link doc
 	@git push origin :v$(shell npm -v) 2>&1 || true
-	git push origin $(BRANCH) &&\
+	@npm unpublish npm@$(shell npm -v) 2>&1 || true
+	git clean -fd &&\
+	git push origin &&\
 	git push origin --tags &&\
-	npm publish --tag=$(PUBLISHTAG)
+	npm publish &&\
+	make doc-publish &&\
+	make zip-publish
 
-release: gitclean ls-ok markedclean marked-manclean doc-clean doc
-	node cli.js prune --production
+docpublish: doc-publish
+doc-publish: doc
+	# legacy urls
+	for f in $$(find html/doc/{cli,files,misc}/ -name '*.html'); do \
+    j=$$(basename $$f | sed 's|^npm-||g'); \
+    if ! [ -f html/doc/$$j ] && [ $$j != README.html ] && [ $$j != index.html ]; then \
+      perl -pi -e 's/ href="\.\.\// href="/g' <$$f >html/doc/$$j; \
+    fi; \
+  done
+	mkdir -p html/api
+	for f in $$(find html/doc/api/ -name '*.html'); do \
+    j=$$(basename $$f | sed 's|^npm-||g'); \
+    perl -pi -e 's/ href="\.\.\// href="/g' <$$f >html/api/$$j; \
+  done
+	rsync -vazu --stats --no-implied-dirs --delete \
+    html/doc/* \
+    ../npm-www/doc
+	rsync -vazu --stats --no-implied-dirs --delete \
+    html/static/style.css \
+    ../npm-www/static/
+	#cleanup
+	rm -rf html/api
+	for f in html/doc/*.html; do \
+    case $$f in \
+      html/doc/README.html) continue ;; \
+      html/doc/index.html) continue ;; \
+      *) rm $$f ;; \
+    esac; \
+  done
+
+zip-publish: release
+	scp release/* node@nodejs.org:dist/npm/
+
+release:
 	@bash scripts/release.sh
 
 sandwich:
 	@[ $$(whoami) = "root" ] && (echo "ok"; echo "ham" > sandwich) || (echo "make it yourself" && exit 13)
 
-.PHONY: all latest install dev link doc clean uninstall test man doc-clean docclean release ls-ok realclean
+.PHONY: all latest install dev link doc clean uninstall test man doc-publish doc-clean docclean docpublish release zip-publish
